apiVersion: v1
kind: Service
metadata:
  name: gemini-chat-service
spec:
  type: ClusterIP   # optional (default is ClusterIP)
  selector:
    app: gemini-chat
  ports:
    - port: 80
      targetPort: 8080